name: WoodCutter
main: se.enji.WoodCutter
authors: [enjikaka, RoyCurtis]
website: http://minecraft.jeremy.se/WoodCutter
version: 1.5.1
api-version: '1.13'

permissions:
  woodcutter.use:
    description: Give you access to use WoodCutters features.
    default: op
