name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
        gradle: [ "8.10" ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle (${{ matrix.gradle }})
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ matrix.gradle }}
      - name: Build
        run: gradle build
      - name: Test
        run: gradle test
      - name: Build jars
        run: gradle jar
      - uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar
